// import Head from 'next/head'
// import Image from 'next/image'
import { GetServerSideProps } from 'next'

import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'  
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import {requests} from '../utils/requests';
import getUrl from '../utils/requests';

import {useSelector} from 'react-redux'

interface IhomeInput{
  genre:string,
  results:any
}

interface Istate{
  dark:Boolean
}

export default function Home({results, genre}:IhomeInput) {
  
  const dark = useSelector(function(state:Istate){return state.dark})

  return (
      <div className={dark && 'dark' }>
        <div className='dark:bg-hulu_ bg-white flex flex-col justify-center items-center w-10/10 text-gray ' >
          <Head>
            <title>Hulu Clone</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
          <Nav genre = {genre} />
          <Results results={results}/>      
        </div>
      </div>   
  )
}



export const getServerSideProps: GetServerSideProps = async (context) => {
  const fetchName = context.query.genre?.toString()
  let props = await getUrl(fetchName)
    return {
      props
    }
      
}